[build]
filehash = true

[serve]
no_spa = true

[[hooks]]
stage = "post_build"
command = "bash"
command_arguments = ["-c", "if [ \"${TRUNK_PROFILE}\" = \"release\" ]; then find ${TRUNK_STAGING_DIR} -type f \\( -name '*.wasm' -o -name '*.js' -o -name '*.html' -o -name '*.css' \\) -exec brotli -f -q 11 {} \\;; fi"]
